# Grammar of Graphics

## Why Graphs?
As you can see from the syllabus, we will spend a lot of time on making graphs. Why? Because humans are visual animals. We can understand things better when we see them. There are reasons why New York Times hire the best graphic designers to make their graphs.

Graphs are no replacement for text. We need both. Text is essnetial to convey complex ideas, caveats, which are always essential in scientific writings. However, graphs are also essential. People are busy, most people will only skim through your papers, so if you want maximum impact, you need to essemtailly make the big pictures and main results as clear as possible in figures. 

The software development has seen a huge burst in making figures. There are many frameworks to do thing, But I will focus on `ggplot2` because it is the right way about thinking about graphs. Just as we learn grammar when we learn a new human language, we need to learn the grammar of graphics when we learn the language of data visualization.

## Our first graph with `ggplot2`
Then we quickly visualize the data using the `ggplot2` package. Suppose we want to see how the flipper length of penguins (encoded as `flipper_length_mm` in the dataset) is related to their body mass (encoded as `body_mass_g`).
```{r}
#| warning: false
library(palmerpenguins) 
data(package = "palmerpenguins") 
library(ggplot2) # <1>
ggplot(
  data = penguins, # <2>
  aes(x = flipper_length_mm, y = body_mass_g) # <3>
) + 
  geom_point() # <4>
```
1. Load the `ggplot2` package.
2. Specify the dataset used in the plot.
3. Define the aesthetics of the plot. Here, we map the flipper length to the x-axis and body mass to the y-axis.
4. Add a layer of points to the plot.


## Why Always Plot Your Data
<!-- https://tellingstorieswithdata.com/05-graphs_tables_maps.html -->