project:
  type: book
  output-dir: docs

book:
  title: "EE BIOL C234"
  subtitle: "Practical Computing for Evolutionary Biologists and Ecologists"
  author: "Chuliang Song"
  date: today
  site-url: https://clsong.github.io/EEB_C234/
  sidebar:
    collapse-level: 2
  google-analytics: 
    tracking-id: "G-WQWBVET0L7"
  chapters:
    - index.qmd
    - 01_intro.qmd

    - part: "A First Look at R"
      chapters:
        - 02_R_basics.qmd
        - 03_data_structure.qmd

    - part: "Grammar of Graphics"
      chapters:
        - 04_ggplot_basic.qmd
        - 05_ggplot_organization.qmd
        - 06_good_plots.qmd
        - PSet1.qmd
        
    - part: "Data Wrangling"
      chapters:
        - 07_dplyr.qmd
        - 08_tidyr.qmd
        - 09_import_data.qmd
    - part: "Visualization by Type"
      chapters:
        - 10_plot_amount.qmd
        - 11_plot_distribution.qmd
        - PSet2.qmd
        - 12_plot_trend.qmd
        - 13_plot_association.qmd
        - 14_plot_others.qmd
        - 15_color.qmd
    - part: "R Programming"
      chapters:
        - 16_vectorization.qmd
        - 17_nested.qmd
        - 18_function.qmd
        - 19_purrr.qmd
        - 20_fast_code.qmd
    #     - PSet3.qmd
    #- part: "Advanced Visualization"
    # - part: "Reproducible Research"
    #   chapters:
    #     - quarto.qmd
    # - references.qmd


bibliography: references.bib
code-annotations: hover

format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-link: true
    df-print: paged

engine: knitr

filters:
  - line-highlight
  - webr