project:
  type: book
  output-dir: docs

book:
  title: "EE BIOL C234"
  subtitle: "Practical Computing for Evolutionary Biologists and Ecologists"
  author: "Chuliang Song"
  date: today
  site-url: https://clsong.github.io/EEB_C234/
  sidebar:
    collapse-level: 2
  google-analytics: 
    tracking-id: "G-WQWBVET0L7"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - part: "A First Look at R"
      chapters:
        - 02_R_basics.qmd
        - 03_data_structure.qmd
    - part: "Grammar of Graphics"
      chapters:
        - 04_ggplot_basic.qmd
        - 05_ggplot_organization.qmd
        - 06_good_plots.qmd
        - PSet1.qmd
    - part: "Data Wrangling"
      chapters:
        - 08_dplyr.qmd
        - 09_tidyr.qmd
        - 10_import_data.qmd
    #     - PSet2.qmd
    # - part: "Visualization"
    #   chapters:
    #     - 07_plots_distribution.qmd
    # - part: "Hierarchical Data"
    #   chapters:
    #     - 12_hierarchical.qmd
    #     - 13_purrr.qmd
    #     - PSet3.qmd
    # - part: "Reproducible Research"
    #   chapters:
    #     - quarto.qmd
    # - references.qmd


bibliography: references.bib
code-annotations: hover

format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-link: true
    df-print: paged

filters:
  - line-highlight
  - webr