project:
  type: book
  output-dir: docs

book:
  title: "EE BIOL C234"
  subtitle: "Practical Computing for Evolutionary Biologists and Ecologists"
  author: "Chuliang Song"
  date: "Winter 2025"
  site-url: https://clsong.github.io/EEB_C234/
  chapters:
    - index.qmd
    - 01_intro.qmd
    # - 02_R_basics.qmd
    # - ggplot_basic.qmd
    # - references.qmd

bibliography: references.bib
code-annotations: hover

format:
    html:
        theme:
            - cosmo
            - style.scss
        df-print: paged
