project:
  type: book
  output-dir: docs

book:
  title: "EE BIOL C234"
  subtitle: "Practical Computing for Evolutionary Biologists and Ecologists"
  author: "Chuliang Song"
  date: today
  site-url: https://clsong.github.io/EEB_C234/
  google-analytics: "G-WQWBVET0L7"
  chapters:
    - index.qmd
    - 01_intro.qmd
    # - 02_R_basics.qmd
    # - 03_data_structure.qmd
    # - 04_ggplot_basic.qmd
    # - references.qmd


bibliography: references.bib
code-annotations: hover

format:
  html:
    theme:
      - cosmo
      - style.scss
    code-link: true
    df-print: paged
    include-in-header:
      - text: |
          <!-- Cronitor RUM -->
          <script async src="https://rum.cronitor.io/script.js"></script>
          <script>
              window.cronitor = window.cronitor || function() { (window.cronitor.q = window.cronitor.q || []).push(arguments); };
              cronitor('config', { clientKey: '46cca0fcdd01fadc7a28ede362e3288e' });
          </script>



filters:
  - line-highlight
