on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  repository_dispatch:
    types: [check-link]

name: Broken Link Check

# Add permissions block
permissions:
  contents: read
  issues: write    # Required for creating/updating issues
  pull-requests: read

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
